# Generated by Django 6.0.3 on 2026-03-19 13:30

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('plot', models.TextField()),
                ('embedding', django_mongodb_backend.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=1024)),
            ],
            options={
                'db_table': 'recommendation_movies',
            },
        ),
    ]
