version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: "3.13-bookworm"
    volumes:
      - ..:/workspaces/20260321_PythonAsia2026:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    # Link to MongoDB service
